# Generated by Django 3.2.6 on 2021-09-20 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Datos del cliente',
                'verbose_name_plural': 'Datos de los clientes',
            },
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('nro_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=100, verbose_name='Dirección')),
                ('referencia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dirección del cliente Delivery',
                'verbose_name_plural': 'Dirección del cliente Delivery',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Breve descripción del producto')),
                ('contenido', models.CharField(max_length=255, verbose_name='Contenido del producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img')),
                ('extra', models.FileField(blank=True, null=True, upload_to='assets')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Productos que contiene el Pedido')),
                ('detalles', models.CharField(max_length=255, verbose_name='Gustos del cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
                ('coordenada', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.coordenada')),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.direccion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.local')),
            ],
        ),
    ]
