# Generated by Django 3.2.6 on 2021-09-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nro_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('DNI', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Datos del cliente',
                'verbose_name_plural': 'Datos de los clientes',
            },
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('nro_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
            options={
                'verbose_name': 'Coordenada del cliente Delivery',
                'verbose_name_plural': 'Coordenada del cliente Delivery',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('nro_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=100, verbose_name='Dirección')),
                ('referencia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dirección del cliente Delivery',
                'verbose_name_plural': 'Dirección del cliente Delivery',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('ID_local', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descripcion', models.TextField(verbose_name='Breve descripción del producto')),
                ('contenido', models.CharField(max_length=255, verbose_name='Contenido del producto')),
                ('cliente_ID', models.ManyToManyField(to='api.Cliente')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('nro_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Productos que contiene el Pedido')),
                ('detalles', models.CharField(max_length=255, verbose_name='Gustos del cliente')),
                ('coordenada_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordenada')),
                ('direccion_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direccion')),
                ('local_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.local')),
                ('producto_ID', models.ManyToManyField(to='api.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='coordenada_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordenada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='local_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.local'),
        ),
    ]
