# Generated by Django 3.2.6 on 2021-09-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contenido', models.CharField(max_length=255, verbose_name='Contenido del producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='promociones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.promociones'),
        ),
    ]
