# Generated by Django 3.2.6 on 2021-09-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210919_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promociones',
            options={'verbose_name': 'Promociones', 'verbose_name_plural': 'Promociones'},
        ),
    ]
