-- MySQL Script generated by MySQL Workbench
-- Tue Sep 14 23:39:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DonRestaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DonRestaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DonRestaurante` DEFAULT CHARACTER SET utf8 ;
USE `DonRestaurante` ;

-- -----------------------------------------------------
-- Table `DonRestaurante`.`LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`LOCAL` (
  `ID_local` INT NOT NULL AUTO_INCREMENT,
  `latitud` VARCHAR(45) NOT NULL,
  `longitud` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_local`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonRestaurante`.`DIRECCIÓN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`DIRECCIÓN` (
  `nro_pedido` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `zona` VARCHAR(255) NULL,
  `referencia` VARCHAR(255) NULL,
  PRIMARY KEY (`nro_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonRestaurante`.`COORDENADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`COORDENADA` (
  `nro_pedido` INT NOT NULL AUTO_INCREMENT,
  `LATITUD` VARCHAR(45) NOT NULL,
  `LONGITUD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nro_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonRestaurante`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`CLIENTE` (
  `nro_cliente` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(20) NULL,
  `nombre` VARCHAR(255) NULL,
  `celular` VARCHAR(20) NULL,
  `LOCAL_ID_local` INT NOT NULL,
  `DIRECCIÓN_nro_pedido` INT NOT NULL,
  `COORDENADA_nro_pedido` INT NOT NULL,
  PRIMARY KEY (`nro_cliente`),
  INDEX `fk_CLIENTE_LOCAL1_idx` (`LOCAL_ID_local` ASC) VISIBLE,
  INDEX `fk_CLIENTE_DIRECCIÓN1_idx` (`DIRECCIÓN_nro_pedido` ASC) VISIBLE,
  INDEX `fk_CLIENTE_COORDENADA1_idx` (`COORDENADA_nro_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_LOCAL1`
    FOREIGN KEY (`LOCAL_ID_local`)
    REFERENCES `DonRestaurante`.`LOCAL` (`ID_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_DIRECCIÓN1`
    FOREIGN KEY (`DIRECCIÓN_nro_pedido`)
    REFERENCES `DonRestaurante`.`DIRECCIÓN` (`nro_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_COORDENADA1`
    FOREIGN KEY (`COORDENADA_nro_pedido`)
    REFERENCES `DonRestaurante`.`COORDENADA` (`nro_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonRestaurante`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`PRODUCTO` (
  `Id-cod` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `precio` DECIMAL NULL,
  `imagen` VARCHAR(255) NULL,
  `img-vid` VARCHAR(255) NULL,
  `descuento` DECIMAL NULL,
  `descripcion` VARCHAR(255) NULL,
  `contenido` VARCHAR(255) NULL,
  PRIMARY KEY (`Id-cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonRestaurante`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`PEDIDO` (
  `nro_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `detalle` VARCHAR(255) NULL,
  `DIRECCIÓN_nro_pedido` INT NOT NULL,
  `COORDENADA_nro_pedido` INT NOT NULL,
  `LOCAL_ID_local` INT NOT NULL,
  PRIMARY KEY (`nro_pedido`),
  INDEX `fk_PEDIDO_DIRECCIÓN1_idx` (`DIRECCIÓN_nro_pedido` ASC) VISIBLE,
  INDEX `fk_PEDIDO_COORDENADA1_idx` (`COORDENADA_nro_pedido` ASC) VISIBLE,
  INDEX `fk_PEDIDO_LOCAL1_idx` (`LOCAL_ID_local` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_DIRECCIÓN1`
    FOREIGN KEY (`DIRECCIÓN_nro_pedido`)
    REFERENCES `DonRestaurante`.`DIRECCIÓN` (`nro_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_COORDENADA1`
    FOREIGN KEY (`COORDENADA_nro_pedido`)
    REFERENCES `DonRestaurante`.`COORDENADA` (`nro_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_LOCAL1`
    FOREIGN KEY (`LOCAL_ID_local`)
    REFERENCES `DonRestaurante`.`LOCAL` (`ID_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonRestaurante`.`CLIENTE_has_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`CLIENTE_has_PRODUCTO` (
  `CLIENTE_nro_cliente` INT NOT NULL,
  `PRODUCTO_Id-cod` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_nro_cliente`, `PRODUCTO_Id-cod`),
  INDEX `fk_CLIENTE_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_Id-cod` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PRODUCTO_CLIENTE_idx` (`CLIENTE_nro_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_CLIENTE`
    FOREIGN KEY (`CLIENTE_nro_cliente`)
    REFERENCES `DonRestaurante`.`CLIENTE` (`nro_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_Id-cod`)
    REFERENCES `DonRestaurante`.`PRODUCTO` (`Id-cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonRestaurante`.`PEDIDO_has_PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonRestaurante`.`PEDIDO_has_PRODUCTO` (
  `PEDIDO_nro_pedido` INT NOT NULL,
  `PRODUCTO_Id-cod` INT NOT NULL,
  PRIMARY KEY (`PEDIDO_nro_pedido`, `PRODUCTO_Id-cod`),
  INDEX `fk_PEDIDO_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_Id-cod` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PRODUCTO_PEDIDO1_idx` (`PEDIDO_nro_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_nro_pedido`)
    REFERENCES `DonRestaurante`.`PEDIDO` (`nro_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_Id-cod`)
    REFERENCES `DonRestaurante`.`PRODUCTO` (`Id-cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
